"""Pydantic models for code review findings and reports."""

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, Field


class Severity(StrEnum):
    """Severity level for a finding."""

    CRITICAL = "critical"
    WARNING = "warning"
    SUGGESTION = "suggestion"


class Category(StrEnum):
    """Category of code review finding."""

    # Logic
    BUG = "bug"
    EDGE_CASE = "edge-case"
    NULL_REFERENCE = "null-reference"
    OFF_BY_ONE = "off-by-one"
    RACE_CONDITION = "race-condition"
    TYPE_ERROR = "type-error"

    # Style
    NAMING = "naming"
    COMPLEXITY = "complexity"
    DUPLICATION = "duplication"
    READABILITY = "readability"
    BEST_PRACTICE = "best-practice"

    # Security
    SQL_INJECTION = "sql-injection"
    XSS = "xss"
    HARDCODED_SECRET = "hardcoded-secret"
    INPUT_VALIDATION = "input-validation"
    INSECURE_DESERIALIZATION = "insecure-deserialization"
    PATH_TRAVERSAL = "path-traversal"
    DEPENDENCY_RISK = "dependency-risk"


class Finding(BaseModel):
    """A single code review finding from a specialist agent."""

    file: str = Field(description="File path relative to repo root")
    line: int = Field(ge=1, description="Line number where the issue occurs")
    severity: Severity = Field(description="How critical this finding is")
    category: Category = Field(description="Type of issue found")
    agent: Literal["logic", "style", "security"] = Field(
        description="Which agent produced this finding"
    )
    message: str = Field(
        max_length=500,
        description="Clear explanation of the issue",
    )
    suggestion: str = Field(
        max_length=500,
        description="Concrete fix recommendation",
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Agent's confidence in this finding (0.0 to 1.0)",
    )


class AgentFindings(BaseModel):
    """Output from a single specialist agent."""

    agent: Literal["logic", "style", "security"]
    findings: list[Finding] = Field(default_factory=list)
    summary: str = Field(
        max_length=300,
        description="Brief summary of what the agent found",
    )


class ReviewReport(BaseModel):
    """Final consolidated review report from the orchestrator."""

    pr_url: str
    pr_title: str = ""
    total_findings: int = 0
    critical_count: int = 0
    warning_count: int = 0
    suggestion_count: int = 0
    findings: list[Finding] = Field(default_factory=list)
    summary: str = Field(
        default="",
        description="Executive summary of the review",
    )

    def format_markdown(self) -> str:
        """Format the review report as a markdown string for GitHub comments."""
        lines: list[str] = []
        lines.append("## 🔍 CodeAgent Review\n")
        lines.append(self.summary + "\n")

        # Stats bar
        lines.append(
            f"**{self.total_findings}** findings: "
            f"🔴 {self.critical_count} critical · "
            f"🟡 {self.warning_count} warnings · "
            f"💡 {self.suggestion_count} suggestions\n"
        )
        lines.append("---\n")

        # Group findings by severity
        for severity in [Severity.CRITICAL, Severity.WARNING, Severity.SUGGESTION]:
            severity_findings = [f for f in self.findings if f.severity == severity]
            if not severity_findings:
                continue

            icon = {"critical": "🔴", "warning": "🟡", "suggestion": "💡"}[severity.value]
            lines.append(f"### {icon} {severity.value.capitalize()}\n")

            for finding in severity_findings:
                lines.append(
                    f"- **`{finding.file}:{finding.line}`** [{finding.category.value}] "
                    f"— {finding.message}\n"
                    f"  > 💡 {finding.suggestion}\n"
                )

        lines.append("\n---\n")
        lines.append(
            "*Generated by [CodeAgent](https://github.com/Enoch-Nemili/codeagent-ai) — "
            "AI-powered multi-agent code review*"
        )
        return "\n".join(lines)
